In [1]:
#import Libraries
import pandas as pd
import numpy as np
import os
from sklearn import linear_model

In [2]:
#import data frame
gdp_df = pd.read_csv("gdp_income .csv")
gdp_df.head()

,Year,GDP (Dollars),Population (No. of People),Disposable Personal Income (Millions of Dollars),Personal Income (Millions of Dollars),Per Capita Disposable Personal Income (Dollars),Per Capita Personal Income (Dollars)
0,1969,"$962,901.70","201,298,000","$687,425.00","$791,229.00","$3,415","$3,931"
1,1970,"$1,012,299.30","203,798,722","$753,099.00","$855,525.00","$3,695","$4,198"
2,1971,"$1,097,173.40","206,817,509","$823,437.00","$924,613.00","$3,981","$4,471"
3,1972,"$1,210,292.40","209,274,882","$893,321.00","$1,016,408.00","$4,269","$4,857"
4,1973,"$1,356,499.70","211,349,205","$1,001,571.00","$1,133,468.00","$4,739","$5,363"

In [3]:
#Convert Data into a working format (removing "$"'s and ","'s )

colstocheck = gdp_df.columns
gdp_df[colstocheck] = gdp_df[colstocheck].replace({'\$':''}, regex = True)
gdp_df[colstocheck] = gdp_df[colstocheck].replace({'\,':''}, regex = True)
gdp_df.head()

,Year,GDP (Dollars),Population (No. of People),Disposable Personal Income (Millions of Dollars),Personal Income (Millions of Dollars),Per Capita Disposable Personal Income (Dollars),Per Capita Personal Income (Dollars)
0,1969,962901.70,201298000,687425.00,791229.00,3415,3931
1,1970,1012299.30,203798722,753099.00,855525.00,3695,4198
2,1971,1097173.40,206817509,823437.00,924613.00,3981,4471
3,1972,1210292.40,209274882,893321.00,1016408.00,4269,4857
4,1973,1356499.70,211349205,1001571.00,1133468.00,4739,5363

In [4]:
#Regressing all Variables 

gdp_reg = linear_model.LinearRegression()
gdp_reg.fit(gdp_df[["Population (No. of People)","Disposable Personal Income (Millions of Dollars)", "Personal Income (Millions of Dollars)","Per Capita Disposable Personal Income (Dollars)","Per Capita Personal Income (Dollars)"]], gdp_df[["GDP (Dollars)"]])

#Printing Coef's and Int for all varible regression
print(gdp_reg.coef_, gdp_reg.intercept_)

print(f'----- The regression equation when regressing ALL variables is: GDP = 0.0264(Population) + .5383(Disposable Income) + .7765(Personal Income) - 108.9833(Disposable Income Per Capita) + 2.4156 (Personal Income Per Capita) -5190895.8857 -----')

[[ 2.64973810e-02  5.38315642e-01  7.76581958e-01 -1.08983321e+02
   2.41566058e+00]] [-5190895.88578392]
----- The regression equation when regressing ALL variables is: GDP = 0.0264(Population) + .5383(Disposable Income) + .7765(Personal Income) - 108.9833(Disposable Income Per Capita) + 2.4156 (Personal Income Per Capita) -5190895.8857 -----

In [5]:
#Regressing only "per capita" Variables and population
gdp_reg2 = linear_model.LinearRegression()
gdp_reg2.fit(gdp_df[["Population (No. of People)","Per Capita Disposable Personal Income (Dollars)","Per Capita Personal Income (Dollars)"]], gdp_df[["GDP (Dollars)"]])

#Printing Coef's and Int for "Per Capita" varible regression
print(gdp_reg2.coef_, gdp_reg2.intercept_)
print(f'----- When regressing "Per Capita" and Population on GDP the equation is: GDP = -0.0583(Population) + 500.6322(Disposable Income Per Capita) + 99.3041(Personal Income Per Capita) + 10395012.3497 -----')

[[-5.83398826e-02  5.00632252e+02  9.93041999e+01]] [10395012.34976435]
----- When regressing "Per Capita" and Population on GDP the equation is: GDP = -0.0583(Population) + 500.6322(Disposable Income Per Capita) + 99.3041(Personal Income Per Capita) + 10395012.3497 -----

In [6]:
#Regressing only "Macro Variables" Variables and population
gdp_reg3 = linear_model.LinearRegression()
gdp_reg3.fit(gdp_df[["Population (No. of People)","Disposable Personal Income (Millions of Dollars)", "Personal Income (Millions of Dollars)"]], gdp_df[["GDP (Dollars)"]])

#Printing Coef's and Int for "Macro Variables" varible regression
print(gdp_reg3.coef_, gdp_reg3.intercept_)
print(f' ----- When regressing "Macro Varaibles" and Population on GDP the equation is: GDP = .0125(Population) + .3940 (Disposable Income) + .7299(Personal Income) - 2590904.4722 -----')

[[0.01254426 0.39400847 0.72997769]] [-2590904.47222796]
 ----- When regressing "Macro Varaibles" and Population on GDP the equation is: GDP = .0125(Population) + .3940 (Disposable Income) + .7299(Personal Income) - 2590904.4722 -----