In [40]:
#Dependencies

import pandas as pd
import numpy as np
import scipy.stats as sts

In [41]:
#Csv read

gdp_income_df=pd.read_csv("EXCEL_gdp_income.csv")
gdp_income_df

,Year,GDP (Dollars),Population (No. of People),Disposable Personal Income (Millions of Dollars),Personal Income (Millions of Dollars),Per Capita Disposable Personal Income (Dollars),Per Capita Personal Income (Dollars)
0,1969,"$962,901.70","201,298,000","$687,425.00","$791,229.00","$3,415","$3,931"
1,1970,"$1,012,299.30","203,798,722","$753,099.00","$855,525.00","$3,695","$4,198"
2,1971,"$1,097,173.40","206,817,509","$823,437.00","$924,613.00","$3,981","$4,471"
3,1972,"$1,210,292.40","209,274,882","$893,321.00","$1,016,408.00","$4,269","$4,857"
4,1973,"$1,356,499.70","211,349,205","$1,001,571.00","$1,133,468.00","$4,739","$5,363"
5,1974,"$1,472,024.20","213,333,635","$1,094,397.00","$1,244,912.00","$5,130","$5,836"
6,1975,"$1,602,227.60","215,456,585","$1,215,359.00","$1,362,505.00","$5,641","$6,324"
7,1976,"$1,780,497.30","217,553,859","$1,323,488.00","$1,495,704.00","$6,083","$6,875"
8,1977,"$1,986,407.70","219,760,875","$1,454,268.00","$1,651,632.00","$6,618","$7,516"
9,1978,"$2,243,230.10","222,098,244","$1,626,753.00","$1,855,849.00","$7,324","$8,356"
10,1979,"$2,489,416.50","224,568,579","$1,805,001.00","$2,073,257.00","$8,038","$9,232"
11,1980,"$2,713,932.70","227,224,719","$2,014,396.00","$2,313,160.00","$8,865","$10,180"
12,1981,"$3,057,318.10","229,465,744","$2,248,034.00","$2,592,915.00","$9,797","$11,300"
13,1982,"$3,211,369.70","231,664,432","$2,426,023.00","$2,779,794.00","$10,472","$11,999"
14,1983,"$3,445,371.90","233,792,014","$2,616,717.00","$2,968,676.00","$11,192","$12,698"
15,1984,"$3,853,668.00","235,824,907","$2,902,515.00","$3,279,488.00","$12,308","$13,906"
16,1985,"$4,126,663.90","237,923,734","$3,093,703.00","$3,510,471.00","$13,003","$14,755"
17,1986,"$4,340,812.60","240,132,831","$3,282,912.00","$3,719,647.00","$13,671","$15,490"
18,1987,"$4,649,020.40","242,288,936","$3,458,192.00","$3,946,593.00","$14,273","$16,289"
19,1988,"$5,053,003.30","244,499,004","$3,763,033.00","$4,267,813.00","$15,391","$17,455"
20,1989,"$5,366,079.60","246,819,222","$4,043,179.00","$4,609,667.00","$16,381","$18,676"
21,1990,"$5,651,746.70","249,622,814","$4,304,512.00","$4,897,821.00","$17,244","$19,621"
22,1991,"$5,842,664.70","252,980,941","$4,479,825.00","$5,067,291.00","$17,708","$20,030"
23,1992,"$6,167,644.20","256,514,224","$4,798,176.00","$5,409,920.00","$18,705","$21,090"
24,1993,"$6,467,697.50","259,918,588","$5,000,936.00","$5,648,732.00","$19,240","$21,733"
25,1994,"$6,912,843.50","263,125,821","$5,247,927.00","$5,940,128.00","$19,945","$22,575"
26,1995,"$7,299,371.50","266,278,393","$5,538,573.00","$6,286,143.00","$20,800","$23,607"
27,1996,"$7,749,965.40","269,394,284","$5,836,986.00","$6,673,186.00","$21,667","$24,771"
28,1997,"$8,284,431.70","272,646,925","$6,156,053.00","$7,086,935.00","$22,579","$25,993"
29,1997,"$8,577,552.00","272,646,925","$6,156,053.00","$7,086,935.00","$22,579","$25,993"
30,1998,"$9,062,817.00","275,854,104","$6,570,164.00","$7,601,594.00","$23,818","$27,557"
31,1999,"$9,630,663.00","279,040,168","$6,890,679.00","$8,001,563.00","$24,694","$28,675"
32,2000,"$10,252,347.00","282,162,411","$7,415,075.00","$8,650,325.00","$26,279","$30,657"
33,2001,"$10,581,822.00","284,968,955","$7,763,912.00","$9,001,839.00","$27,245","$31,589"
34,2002,"$10,936,418.00","287,625,193","$8,104,480.00","$9,155,663.00","$28,177","$31,832"
35,2003,"$11,458,246.00","290,107,933","$8,478,455.00","$9,480,901.00","$29,225","$32,681"
36,2004,"$12,213,730.00","292,805,298","$8,981,157.00","$10,028,781.00","$30,673","$34,251"
37,2005,"$13,036,637.00","295,516,599","$9,382,761.00","$10,593,946.00","$31,750","$35,849"
38,2006,"$13,814,609.00","298,379,912","$10,017,121.00","$11,372,589.00","$33,572","$38,114"
39,2007,"$14,451,860.00","301,231,207","$10,511,373.00","$12,002,204.00","$34,895","$39,844"
40,2008,"$14,712,845.00","304,093,966","$10,932,716.00","$12,438,527.00","$35,952","$40,904"
41,2009,"$14,448,932.00","306,771,529","$10,900,400.00","$12,051,307.00","$35,533","$39,284"
42,2010,"$14,992,052.00","309,327,143","$11,305,991.00","$12,541,995.00","$36,550","$40,546"
43,2011,"$15,542,582.00","311,583,481","$11,863,823.00","$13,315,478.00","$38,076","$42,735"
44,2012,"$16,197,007.00","313,877,662","$12,490,913.00","$13,998,383.00","$39,795","$44,598"
45,2013,"$16,784,851.00","316,059,947","$12,501,275.00","$14,175,503.00","$39,553","$44,851"
46,2014,"$17,527,258.00","318,386,329","$13,200,377.00","$14,982,715.00","$41,460","$47,058"
47,2015,"$18,238,301.00","320,738,994","$13,779,697.00","$15,717,140.00","$42,962","$49,003"
48,2016,"$18,745,075.00","323,071,755","$14,196,265.00","$16,151,881.00","$43,942","$49,995"
49,2017,"$19,542,980.00","325,122,128","$14,894,009.00","$16,937,582.00","$45,811","$52,096"
50,2018,"$20,611,861.00","326,838,199","$15,757,141.00","$17,839,255.00","$48,211","$54,581"
51,2019,"$21,433,226.00","328,329,953","$16,342,277.00","$18,542,262.00","$49,774","$56,474"

In [42]:
#Replacing $ and , 

gdp_income_df["GDP (Dollars)"]=gdp_income_df["GDP (Dollars)"].str.replace('$', '')
gdp_income_df["GDP (Dollars)"]=gdp_income_df["GDP (Dollars)"].str.replace(',', '')
gdp_income_df["GDP (Dollars)"]=gdp_income_df["GDP (Dollars)"].astype(float)
gdp_income_df

<ipython-input-42-dde04f15043d>:3: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  gdp_income_df["GDP (Dollars)"]=gdp_income_df["GDP (Dollars)"].str.replace('$', '')

,Year,GDP (Dollars),Population (No. of People),Disposable Personal Income (Millions of Dollars),Personal Income (Millions of Dollars),Per Capita Disposable Personal Income (Dollars),Per Capita Personal Income (Dollars)
0,1969,962901.7,"201,298,000","$687,425.00","$791,229.00","$3,415","$3,931"
1,1970,1012299.3,"203,798,722","$753,099.00","$855,525.00","$3,695","$4,198"
2,1971,1097173.4,"206,817,509","$823,437.00","$924,613.00","$3,981","$4,471"
3,1972,1210292.4,"209,274,882","$893,321.00","$1,016,408.00","$4,269","$4,857"
4,1973,1356499.7,"211,349,205","$1,001,571.00","$1,133,468.00","$4,739","$5,363"
5,1974,1472024.2,"213,333,635","$1,094,397.00","$1,244,912.00","$5,130","$5,836"
6,1975,1602227.6,"215,456,585","$1,215,359.00","$1,362,505.00","$5,641","$6,324"
7,1976,1780497.3,"217,553,859","$1,323,488.00","$1,495,704.00","$6,083","$6,875"
8,1977,1986407.7,"219,760,875","$1,454,268.00","$1,651,632.00","$6,618","$7,516"
9,1978,2243230.1,"222,098,244","$1,626,753.00","$1,855,849.00","$7,324","$8,356"
10,1979,2489416.5,"224,568,579","$1,805,001.00","$2,073,257.00","$8,038","$9,232"
11,1980,2713932.7,"227,224,719","$2,014,396.00","$2,313,160.00","$8,865","$10,180"
12,1981,3057318.1,"229,465,744","$2,248,034.00","$2,592,915.00","$9,797","$11,300"
13,1982,3211369.7,"231,664,432","$2,426,023.00","$2,779,794.00","$10,472","$11,999"
14,1983,3445371.9,"233,792,014","$2,616,717.00","$2,968,676.00","$11,192","$12,698"
15,1984,3853668.0,"235,824,907","$2,902,515.00","$3,279,488.00","$12,308","$13,906"
16,1985,4126663.9,"237,923,734","$3,093,703.00","$3,510,471.00","$13,003","$14,755"
17,1986,4340812.6,"240,132,831","$3,282,912.00","$3,719,647.00","$13,671","$15,490"
18,1987,4649020.4,"242,288,936","$3,458,192.00","$3,946,593.00","$14,273","$16,289"
19,1988,5053003.3,"244,499,004","$3,763,033.00","$4,267,813.00","$15,391","$17,455"
20,1989,5366079.6,"246,819,222","$4,043,179.00","$4,609,667.00","$16,381","$18,676"
21,1990,5651746.7,"249,622,814","$4,304,512.00","$4,897,821.00","$17,244","$19,621"
22,1991,5842664.7,"252,980,941","$4,479,825.00","$5,067,291.00","$17,708","$20,030"
23,1992,6167644.2,"256,514,224","$4,798,176.00","$5,409,920.00","$18,705","$21,090"
24,1993,6467697.5,"259,918,588","$5,000,936.00","$5,648,732.00","$19,240","$21,733"
25,1994,6912843.5,"263,125,821","$5,247,927.00","$5,940,128.00","$19,945","$22,575"
26,1995,7299371.5,"266,278,393","$5,538,573.00","$6,286,143.00","$20,800","$23,607"
27,1996,7749965.4,"269,394,284","$5,836,986.00","$6,673,186.00","$21,667","$24,771"
28,1997,8284431.7,"272,646,925","$6,156,053.00","$7,086,935.00","$22,579","$25,993"
29,1997,8577552.0,"272,646,925","$6,156,053.00","$7,086,935.00","$22,579","$25,993"
30,1998,9062817.0,"275,854,104","$6,570,164.00","$7,601,594.00","$23,818","$27,557"
31,1999,9630663.0,"279,040,168","$6,890,679.00","$8,001,563.00","$24,694","$28,675"
32,2000,10252347.0,"282,162,411","$7,415,075.00","$8,650,325.00","$26,279","$30,657"
33,2001,10581822.0,"284,968,955","$7,763,912.00","$9,001,839.00","$27,245","$31,589"
34,2002,10936418.0,"287,625,193","$8,104,480.00","$9,155,663.00","$28,177","$31,832"
35,2003,11458246.0,"290,107,933","$8,478,455.00","$9,480,901.00","$29,225","$32,681"
36,2004,12213730.0,"292,805,298","$8,981,157.00","$10,028,781.00","$30,673","$34,251"
37,2005,13036637.0,"295,516,599","$9,382,761.00","$10,593,946.00","$31,750","$35,849"
38,2006,13814609.0,"298,379,912","$10,017,121.00","$11,372,589.00","$33,572","$38,114"
39,2007,14451860.0,"301,231,207","$10,511,373.00","$12,002,204.00","$34,895","$39,844"
40,2008,14712845.0,"304,093,966","$10,932,716.00","$12,438,527.00","$35,952","$40,904"
41,2009,14448932.0,"306,771,529","$10,900,400.00","$12,051,307.00","$35,533","$39,284"
42,2010,14992052.0,"309,327,143","$11,305,991.00","$12,541,995.00","$36,550","$40,546"
43,2011,15542582.0,"311,583,481","$11,863,823.00","$13,315,478.00","$38,076","$42,735"
44,2012,16197007.0,"313,877,662","$12,490,913.00","$13,998,383.00","$39,795","$44,598"
45,2013,16784851.0,"316,059,947","$12,501,275.00","$14,175,503.00","$39,553","$44,851"
46,2014,17527258.0,"318,386,329","$13,200,377.00","$14,982,715.00","$41,460","$47,058"
47,2015,18238301.0,"320,738,994","$13,779,697.00","$15,717,140.00","$42,962","$49,003"
48,2016,18745075.0,"323,071,755","$14,196,265.00","$16,151,881.00","$43,942","$49,995"
49,2017,19542980.0,"325,122,128","$14,894,009.00","$16,937,582.00","$45,811","$52,096"
50,2018,20611861.0,"326,838,199","$15,757,141.00","$17,839,255.00","$48,211","$54,581"
51,2019,21433226.0,"328,329,953","$16,342,277.00","$18,542,262.00","$49,774","$56,474"

In [43]:
gdp_income_df["Population (No. of People)"]=gdp_income_df["Population (No. of People)"].str.replace('$', '')
gdp_income_df["Population (No. of People)"]=gdp_income_df["Population (No. of People)"].str.replace(',', '')
gdp_income_df["Population (No. of People)"]=gdp_income_df["Population (No. of People)"].astype(int)
gdp_income_df

<ipython-input-43-d5bad422d346>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  gdp_income_df["Population (No. of People)"]=gdp_income_df["Population (No. of People)"].str.replace('$', '')

,Year,GDP (Dollars),Population (No. of People),Disposable Personal Income (Millions of Dollars),Personal Income (Millions of Dollars),Per Capita Disposable Personal Income (Dollars),Per Capita Personal Income (Dollars)
0,1969,962901.7,201298000,"$687,425.00","$791,229.00","$3,415","$3,931"
1,1970,1012299.3,203798722,"$753,099.00","$855,525.00","$3,695","$4,198"
2,1971,1097173.4,206817509,"$823,437.00","$924,613.00","$3,981","$4,471"
3,1972,1210292.4,209274882,"$893,321.00","$1,016,408.00","$4,269","$4,857"
4,1973,1356499.7,211349205,"$1,001,571.00","$1,133,468.00","$4,739","$5,363"
5,1974,1472024.2,213333635,"$1,094,397.00","$1,244,912.00","$5,130","$5,836"
6,1975,1602227.6,215456585,"$1,215,359.00","$1,362,505.00","$5,641","$6,324"
7,1976,1780497.3,217553859,"$1,323,488.00","$1,495,704.00","$6,083","$6,875"
8,1977,1986407.7,219760875,"$1,454,268.00","$1,651,632.00","$6,618","$7,516"
9,1978,2243230.1,222098244,"$1,626,753.00","$1,855,849.00","$7,324","$8,356"
10,1979,2489416.5,224568579,"$1,805,001.00","$2,073,257.00","$8,038","$9,232"
11,1980,2713932.7,227224719,"$2,014,396.00","$2,313,160.00","$8,865","$10,180"
12,1981,3057318.1,229465744,"$2,248,034.00","$2,592,915.00","$9,797","$11,300"
13,1982,3211369.7,231664432,"$2,426,023.00","$2,779,794.00","$10,472","$11,999"
14,1983,3445371.9,233792014,"$2,616,717.00","$2,968,676.00","$11,192","$12,698"
15,1984,3853668.0,235824907,"$2,902,515.00","$3,279,488.00","$12,308","$13,906"
16,1985,4126663.9,237923734,"$3,093,703.00","$3,510,471.00","$13,003","$14,755"
17,1986,4340812.6,240132831,"$3,282,912.00","$3,719,647.00","$13,671","$15,490"
18,1987,4649020.4,242288936,"$3,458,192.00","$3,946,593.00","$14,273","$16,289"
19,1988,5053003.3,244499004,"$3,763,033.00","$4,267,813.00","$15,391","$17,455"
20,1989,5366079.6,246819222,"$4,043,179.00","$4,609,667.00","$16,381","$18,676"
21,1990,5651746.7,249622814,"$4,304,512.00","$4,897,821.00","$17,244","$19,621"
22,1991,5842664.7,252980941,"$4,479,825.00","$5,067,291.00","$17,708","$20,030"
23,1992,6167644.2,256514224,"$4,798,176.00","$5,409,920.00","$18,705","$21,090"
24,1993,6467697.5,259918588,"$5,000,936.00","$5,648,732.00","$19,240","$21,733"
25,1994,6912843.5,263125821,"$5,247,927.00","$5,940,128.00","$19,945","$22,575"
26,1995,7299371.5,266278393,"$5,538,573.00","$6,286,143.00","$20,800","$23,607"
27,1996,7749965.4,269394284,"$5,836,986.00","$6,673,186.00","$21,667","$24,771"
28,1997,8284431.7,272646925,"$6,156,053.00","$7,086,935.00","$22,579","$25,993"
29,1997,8577552.0,272646925,"$6,156,053.00","$7,086,935.00","$22,579","$25,993"
30,1998,9062817.0,275854104,"$6,570,164.00","$7,601,594.00","$23,818","$27,557"
31,1999,9630663.0,279040168,"$6,890,679.00","$8,001,563.00","$24,694","$28,675"
32,2000,10252347.0,282162411,"$7,415,075.00","$8,650,325.00","$26,279","$30,657"
33,2001,10581822.0,284968955,"$7,763,912.00","$9,001,839.00","$27,245","$31,589"
34,2002,10936418.0,287625193,"$8,104,480.00","$9,155,663.00","$28,177","$31,832"
35,2003,11458246.0,290107933,"$8,478,455.00","$9,480,901.00","$29,225","$32,681"
36,2004,12213730.0,292805298,"$8,981,157.00","$10,028,781.00","$30,673","$34,251"
37,2005,13036637.0,295516599,"$9,382,761.00","$10,593,946.00","$31,750","$35,849"
38,2006,13814609.0,298379912,"$10,017,121.00","$11,372,589.00","$33,572","$38,114"
39,2007,14451860.0,301231207,"$10,511,373.00","$12,002,204.00","$34,895","$39,844"
40,2008,14712845.0,304093966,"$10,932,716.00","$12,438,527.00","$35,952","$40,904"
41,2009,14448932.0,306771529,"$10,900,400.00","$12,051,307.00","$35,533","$39,284"
42,2010,14992052.0,309327143,"$11,305,991.00","$12,541,995.00","$36,550","$40,546"
43,2011,15542582.0,311583481,"$11,863,823.00","$13,315,478.00","$38,076","$42,735"
44,2012,16197007.0,313877662,"$12,490,913.00","$13,998,383.00","$39,795","$44,598"
45,2013,16784851.0,316059947,"$12,501,275.00","$14,175,503.00","$39,553","$44,851"
46,2014,17527258.0,318386329,"$13,200,377.00","$14,982,715.00","$41,460","$47,058"
47,2015,18238301.0,320738994,"$13,779,697.00","$15,717,140.00","$42,962","$49,003"
48,2016,18745075.0,323071755,"$14,196,265.00","$16,151,881.00","$43,942","$49,995"
49,2017,19542980.0,325122128,"$14,894,009.00","$16,937,582.00","$45,811","$52,096"
50,2018,20611861.0,326838199,"$15,757,141.00","$17,839,255.00","$48,211","$54,581"
51,2019,21433226.0,328329953,"$16,342,277.00","$18,542,262.00","$49,774","$56,474"

In [44]:
gdp_income_df["Disposable Personal Income (Millions of Dollars)"]=gdp_income_df["Disposable Personal Income (Millions of Dollars)"].str.replace('$', '')
gdp_income_df["Disposable Personal Income (Millions of Dollars)"]=gdp_income_df["Disposable Personal Income (Millions of Dollars)"].str.replace(',', '')
gdp_income_df["Disposable Personal Income (Millions of Dollars)"]=gdp_income_df["Disposable Personal Income (Millions of Dollars)"].astype(float)
gdp_income_df

<ipython-input-44-6912dc0b0225>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  gdp_income_df["Disposable Personal Income (Millions of Dollars)"]=gdp_income_df["Disposable Personal Income (Millions of Dollars)"].str.replace('$', '')

,Year,GDP (Dollars),Population (No. of People),Disposable Personal Income (Millions of Dollars),Personal Income (Millions of Dollars),Per Capita Disposable Personal Income (Dollars),Per Capita Personal Income (Dollars)
0,1969,962901.7,201298000,687425.0,"$791,229.00","$3,415","$3,931"
1,1970,1012299.3,203798722,753099.0,"$855,525.00","$3,695","$4,198"
2,1971,1097173.4,206817509,823437.0,"$924,613.00","$3,981","$4,471"
3,1972,1210292.4,209274882,893321.0,"$1,016,408.00","$4,269","$4,857"
4,1973,1356499.7,211349205,1001571.0,"$1,133,468.00","$4,739","$5,363"
5,1974,1472024.2,213333635,1094397.0,"$1,244,912.00","$5,130","$5,836"
6,1975,1602227.6,215456585,1215359.0,"$1,362,505.00","$5,641","$6,324"
7,1976,1780497.3,217553859,1323488.0,"$1,495,704.00","$6,083","$6,875"
8,1977,1986407.7,219760875,1454268.0,"$1,651,632.00","$6,618","$7,516"
9,1978,2243230.1,222098244,1626753.0,"$1,855,849.00","$7,324","$8,356"
10,1979,2489416.5,224568579,1805001.0,"$2,073,257.00","$8,038","$9,232"
11,1980,2713932.7,227224719,2014396.0,"$2,313,160.00","$8,865","$10,180"
12,1981,3057318.1,229465744,2248034.0,"$2,592,915.00","$9,797","$11,300"
13,1982,3211369.7,231664432,2426023.0,"$2,779,794.00","$10,472","$11,999"
14,1983,3445371.9,233792014,2616717.0,"$2,968,676.00","$11,192","$12,698"
15,1984,3853668.0,235824907,2902515.0,"$3,279,488.00","$12,308","$13,906"
16,1985,4126663.9,237923734,3093703.0,"$3,510,471.00","$13,003","$14,755"
17,1986,4340812.6,240132831,3282912.0,"$3,719,647.00","$13,671","$15,490"
18,1987,4649020.4,242288936,3458192.0,"$3,946,593.00","$14,273","$16,289"
19,1988,5053003.3,244499004,3763033.0,"$4,267,813.00","$15,391","$17,455"
20,1989,5366079.6,246819222,4043179.0,"$4,609,667.00","$16,381","$18,676"
21,1990,5651746.7,249622814,4304512.0,"$4,897,821.00","$17,244","$19,621"
22,1991,5842664.7,252980941,4479825.0,"$5,067,291.00","$17,708","$20,030"
23,1992,6167644.2,256514224,4798176.0,"$5,409,920.00","$18,705","$21,090"
24,1993,6467697.5,259918588,5000936.0,"$5,648,732.00","$19,240","$21,733"
25,1994,6912843.5,263125821,5247927.0,"$5,940,128.00","$19,945","$22,575"
26,1995,7299371.5,266278393,5538573.0,"$6,286,143.00","$20,800","$23,607"
27,1996,7749965.4,269394284,5836986.0,"$6,673,186.00","$21,667","$24,771"
28,1997,8284431.7,272646925,6156053.0,"$7,086,935.00","$22,579","$25,993"
29,1997,8577552.0,272646925,6156053.0,"$7,086,935.00","$22,579","$25,993"
30,1998,9062817.0,275854104,6570164.0,"$7,601,594.00","$23,818","$27,557"
31,1999,9630663.0,279040168,6890679.0,"$8,001,563.00","$24,694","$28,675"
32,2000,10252347.0,282162411,7415075.0,"$8,650,325.00","$26,279","$30,657"
33,2001,10581822.0,284968955,7763912.0,"$9,001,839.00","$27,245","$31,589"
34,2002,10936418.0,287625193,8104480.0,"$9,155,663.00","$28,177","$31,832"
35,2003,11458246.0,290107933,8478455.0,"$9,480,901.00","$29,225","$32,681"
36,2004,12213730.0,292805298,8981157.0,"$10,028,781.00","$30,673","$34,251"
37,2005,13036637.0,295516599,9382761.0,"$10,593,946.00","$31,750","$35,849"
38,2006,13814609.0,298379912,10017121.0,"$11,372,589.00","$33,572","$38,114"
39,2007,14451860.0,301231207,10511373.0,"$12,002,204.00","$34,895","$39,844"
40,2008,14712845.0,304093966,10932716.0,"$12,438,527.00","$35,952","$40,904"
41,2009,14448932.0,306771529,10900400.0,"$12,051,307.00","$35,533","$39,284"
42,2010,14992052.0,309327143,11305991.0,"$12,541,995.00","$36,550","$40,546"
43,2011,15542582.0,311583481,11863823.0,"$13,315,478.00","$38,076","$42,735"
44,2012,16197007.0,313877662,12490913.0,"$13,998,383.00","$39,795","$44,598"
45,2013,16784851.0,316059947,12501275.0,"$14,175,503.00","$39,553","$44,851"
46,2014,17527258.0,318386329,13200377.0,"$14,982,715.00","$41,460","$47,058"
47,2015,18238301.0,320738994,13779697.0,"$15,717,140.00","$42,962","$49,003"
48,2016,18745075.0,323071755,14196265.0,"$16,151,881.00","$43,942","$49,995"
49,2017,19542980.0,325122128,14894009.0,"$16,937,582.00","$45,811","$52,096"
50,2018,20611861.0,326838199,15757141.0,"$17,839,255.00","$48,211","$54,581"
51,2019,21433226.0,328329953,16342277.0,"$18,542,262.00","$49,774","$56,474"

In [45]:
gdp_income_df["Personal Income (Millions of Dollars)"]=gdp_income_df["Personal Income (Millions of Dollars)"].str.replace('$', '')
gdp_income_df["Personal Income (Millions of Dollars)"]=gdp_income_df["Personal Income (Millions of Dollars)"].str.replace(',', '')
gdp_income_df["Personal Income (Millions of Dollars)"]=gdp_income_df["Personal Income (Millions of Dollars)"].astype(float)
gdp_income_df

<ipython-input-45-38cba6bf1f8b>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  gdp_income_df["Personal Income (Millions of Dollars)"]=gdp_income_df["Personal Income (Millions of Dollars)"].str.replace('$', '')

,Year,GDP (Dollars),Population (No. of People),Disposable Personal Income (Millions of Dollars),Personal Income (Millions of Dollars),Per Capita Disposable Personal Income (Dollars),Per Capita Personal Income (Dollars)
0,1969,962901.7,201298000,687425.0,791229.0,"$3,415","$3,931"
1,1970,1012299.3,203798722,753099.0,855525.0,"$3,695","$4,198"
2,1971,1097173.4,206817509,823437.0,924613.0,"$3,981","$4,471"
3,1972,1210292.4,209274882,893321.0,1016408.0,"$4,269","$4,857"
4,1973,1356499.7,211349205,1001571.0,1133468.0,"$4,739","$5,363"
5,1974,1472024.2,213333635,1094397.0,1244912.0,"$5,130","$5,836"
6,1975,1602227.6,215456585,1215359.0,1362505.0,"$5,641","$6,324"
7,1976,1780497.3,217553859,1323488.0,1495704.0,"$6,083","$6,875"
8,1977,1986407.7,219760875,1454268.0,1651632.0,"$6,618","$7,516"
9,1978,2243230.1,222098244,1626753.0,1855849.0,"$7,324","$8,356"
10,1979,2489416.5,224568579,1805001.0,2073257.0,"$8,038","$9,232"
11,1980,2713932.7,227224719,2014396.0,2313160.0,"$8,865","$10,180"
12,1981,3057318.1,229465744,2248034.0,2592915.0,"$9,797","$11,300"
13,1982,3211369.7,231664432,2426023.0,2779794.0,"$10,472","$11,999"
14,1983,3445371.9,233792014,2616717.0,2968676.0,"$11,192","$12,698"
15,1984,3853668.0,235824907,2902515.0,3279488.0,"$12,308","$13,906"
16,1985,4126663.9,237923734,3093703.0,3510471.0,"$13,003","$14,755"
17,1986,4340812.6,240132831,3282912.0,3719647.0,"$13,671","$15,490"
18,1987,4649020.4,242288936,3458192.0,3946593.0,"$14,273","$16,289"
19,1988,5053003.3,244499004,3763033.0,4267813.0,"$15,391","$17,455"
20,1989,5366079.6,246819222,4043179.0,4609667.0,"$16,381","$18,676"
21,1990,5651746.7,249622814,4304512.0,4897821.0,"$17,244","$19,621"
22,1991,5842664.7,252980941,4479825.0,5067291.0,"$17,708","$20,030"
23,1992,6167644.2,256514224,4798176.0,5409920.0,"$18,705","$21,090"
24,1993,6467697.5,259918588,5000936.0,5648732.0,"$19,240","$21,733"
25,1994,6912843.5,263125821,5247927.0,5940128.0,"$19,945","$22,575"
26,1995,7299371.5,266278393,5538573.0,6286143.0,"$20,800","$23,607"
27,1996,7749965.4,269394284,5836986.0,6673186.0,"$21,667","$24,771"
28,1997,8284431.7,272646925,6156053.0,7086935.0,"$22,579","$25,993"
29,1997,8577552.0,272646925,6156053.0,7086935.0,"$22,579","$25,993"
30,1998,9062817.0,275854104,6570164.0,7601594.0,"$23,818","$27,557"
31,1999,9630663.0,279040168,6890679.0,8001563.0,"$24,694","$28,675"
32,2000,10252347.0,282162411,7415075.0,8650325.0,"$26,279","$30,657"
33,2001,10581822.0,284968955,7763912.0,9001839.0,"$27,245","$31,589"
34,2002,10936418.0,287625193,8104480.0,9155663.0,"$28,177","$31,832"
35,2003,11458246.0,290107933,8478455.0,9480901.0,"$29,225","$32,681"
36,2004,12213730.0,292805298,8981157.0,10028781.0,"$30,673","$34,251"
37,2005,13036637.0,295516599,9382761.0,10593946.0,"$31,750","$35,849"
38,2006,13814609.0,298379912,10017121.0,11372589.0,"$33,572","$38,114"
39,2007,14451860.0,301231207,10511373.0,12002204.0,"$34,895","$39,844"
40,2008,14712845.0,304093966,10932716.0,12438527.0,"$35,952","$40,904"
41,2009,14448932.0,306771529,10900400.0,12051307.0,"$35,533","$39,284"
42,2010,14992052.0,309327143,11305991.0,12541995.0,"$36,550","$40,546"
43,2011,15542582.0,311583481,11863823.0,13315478.0,"$38,076","$42,735"
44,2012,16197007.0,313877662,12490913.0,13998383.0,"$39,795","$44,598"
45,2013,16784851.0,316059947,12501275.0,14175503.0,"$39,553","$44,851"
46,2014,17527258.0,318386329,13200377.0,14982715.0,"$41,460","$47,058"
47,2015,18238301.0,320738994,13779697.0,15717140.0,"$42,962","$49,003"
48,2016,18745075.0,323071755,14196265.0,16151881.0,"$43,942","$49,995"
49,2017,19542980.0,325122128,14894009.0,16937582.0,"$45,811","$52,096"
50,2018,20611861.0,326838199,15757141.0,17839255.0,"$48,211","$54,581"
51,2019,21433226.0,328329953,16342277.0,18542262.0,"$49,774","$56,474"

In [46]:
gdp_income_df["Per Capita Disposable Personal Income (Dollars)"]=gdp_income_df["Per Capita Disposable Personal Income (Dollars)"].str.replace('$', '')
gdp_income_df["Per Capita Disposable Personal Income (Dollars)"]=gdp_income_df["Per Capita Disposable Personal Income (Dollars)"].str.replace(',', '')
gdp_income_df["Per Capita Disposable Personal Income (Dollars)"]=gdp_income_df["Per Capita Disposable Personal Income (Dollars)"].astype(int)
gdp_income_df

<ipython-input-46-09ce09cb9fbb>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  gdp_income_df["Per Capita Disposable Personal Income (Dollars)"]=gdp_income_df["Per Capita Disposable Personal Income (Dollars)"].str.replace('$', '')

,Year,GDP (Dollars),Population (No. of People),Disposable Personal Income (Millions of Dollars),Personal Income (Millions of Dollars),Per Capita Disposable Personal Income (Dollars),Per Capita Personal Income (Dollars)
0,1969,962901.7,201298000,687425.0,791229.0,3415,"$3,931"
1,1970,1012299.3,203798722,753099.0,855525.0,3695,"$4,198"
2,1971,1097173.4,206817509,823437.0,924613.0,3981,"$4,471"
3,1972,1210292.4,209274882,893321.0,1016408.0,4269,"$4,857"
4,1973,1356499.7,211349205,1001571.0,1133468.0,4739,"$5,363"
5,1974,1472024.2,213333635,1094397.0,1244912.0,5130,"$5,836"
6,1975,1602227.6,215456585,1215359.0,1362505.0,5641,"$6,324"
7,1976,1780497.3,217553859,1323488.0,1495704.0,6083,"$6,875"
8,1977,1986407.7,219760875,1454268.0,1651632.0,6618,"$7,516"
9,1978,2243230.1,222098244,1626753.0,1855849.0,7324,"$8,356"
10,1979,2489416.5,224568579,1805001.0,2073257.0,8038,"$9,232"
11,1980,2713932.7,227224719,2014396.0,2313160.0,8865,"$10,180"
12,1981,3057318.1,229465744,2248034.0,2592915.0,9797,"$11,300"
13,1982,3211369.7,231664432,2426023.0,2779794.0,10472,"$11,999"
14,1983,3445371.9,233792014,2616717.0,2968676.0,11192,"$12,698"
15,1984,3853668.0,235824907,2902515.0,3279488.0,12308,"$13,906"
16,1985,4126663.9,237923734,3093703.0,3510471.0,13003,"$14,755"
17,1986,4340812.6,240132831,3282912.0,3719647.0,13671,"$15,490"
18,1987,4649020.4,242288936,3458192.0,3946593.0,14273,"$16,289"
19,1988,5053003.3,244499004,3763033.0,4267813.0,15391,"$17,455"
20,1989,5366079.6,246819222,4043179.0,4609667.0,16381,"$18,676"
21,1990,5651746.7,249622814,4304512.0,4897821.0,17244,"$19,621"
22,1991,5842664.7,252980941,4479825.0,5067291.0,17708,"$20,030"
23,1992,6167644.2,256514224,4798176.0,5409920.0,18705,"$21,090"
24,1993,6467697.5,259918588,5000936.0,5648732.0,19240,"$21,733"
25,1994,6912843.5,263125821,5247927.0,5940128.0,19945,"$22,575"
26,1995,7299371.5,266278393,5538573.0,6286143.0,20800,"$23,607"
27,1996,7749965.4,269394284,5836986.0,6673186.0,21667,"$24,771"
28,1997,8284431.7,272646925,6156053.0,7086935.0,22579,"$25,993"
29,1997,8577552.0,272646925,6156053.0,7086935.0,22579,"$25,993"
30,1998,9062817.0,275854104,6570164.0,7601594.0,23818,"$27,557"
31,1999,9630663.0,279040168,6890679.0,8001563.0,24694,"$28,675"
32,2000,10252347.0,282162411,7415075.0,8650325.0,26279,"$30,657"
33,2001,10581822.0,284968955,7763912.0,9001839.0,27245,"$31,589"
34,2002,10936418.0,287625193,8104480.0,9155663.0,28177,"$31,832"
35,2003,11458246.0,290107933,8478455.0,9480901.0,29225,"$32,681"
36,2004,12213730.0,292805298,8981157.0,10028781.0,30673,"$34,251"
37,2005,13036637.0,295516599,9382761.0,10593946.0,31750,"$35,849"
38,2006,13814609.0,298379912,10017121.0,11372589.0,33572,"$38,114"
39,2007,14451860.0,301231207,10511373.0,12002204.0,34895,"$39,844"
40,2008,14712845.0,304093966,10932716.0,12438527.0,35952,"$40,904"
41,2009,14448932.0,306771529,10900400.0,12051307.0,35533,"$39,284"
42,2010,14992052.0,309327143,11305991.0,12541995.0,36550,"$40,546"
43,2011,15542582.0,311583481,11863823.0,13315478.0,38076,"$42,735"
44,2012,16197007.0,313877662,12490913.0,13998383.0,39795,"$44,598"
45,2013,16784851.0,316059947,12501275.0,14175503.0,39553,"$44,851"
46,2014,17527258.0,318386329,13200377.0,14982715.0,41460,"$47,058"
47,2015,18238301.0,320738994,13779697.0,15717140.0,42962,"$49,003"
48,2016,18745075.0,323071755,14196265.0,16151881.0,43942,"$49,995"
49,2017,19542980.0,325122128,14894009.0,16937582.0,45811,"$52,096"
50,2018,20611861.0,326838199,15757141.0,17839255.0,48211,"$54,581"
51,2019,21433226.0,328329953,16342277.0,18542262.0,49774,"$56,474"

In [47]:
gdp_income_df["Per Capita Personal Income (Dollars)"]=gdp_income_df["Per Capita Personal Income (Dollars)"].str.replace('$', '')
gdp_income_df["Per Capita Personal Income (Dollars)"]=gdp_income_df["Per Capita Personal Income (Dollars)"].str.replace(',', '')
gdp_income_df["Per Capita Personal Income (Dollars)"]=gdp_income_df["Per Capita Personal Income (Dollars)"].astype(int)
gdp_income_df

<ipython-input-47-101b769d8415>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  gdp_income_df["Per Capita Personal Income (Dollars)"]=gdp_income_df["Per Capita Personal Income (Dollars)"].str.replace('$', '')

,Year,GDP (Dollars),Population (No. of People),Disposable Personal Income (Millions of Dollars),Personal Income (Millions of Dollars),Per Capita Disposable Personal Income (Dollars),Per Capita Personal Income (Dollars)
0,1969,962901.7,201298000,687425.0,791229.0,3415,3931
1,1970,1012299.3,203798722,753099.0,855525.0,3695,4198
2,1971,1097173.4,206817509,823437.0,924613.0,3981,4471
3,1972,1210292.4,209274882,893321.0,1016408.0,4269,4857
4,1973,1356499.7,211349205,1001571.0,1133468.0,4739,5363
5,1974,1472024.2,213333635,1094397.0,1244912.0,5130,5836
6,1975,1602227.6,215456585,1215359.0,1362505.0,5641,6324
7,1976,1780497.3,217553859,1323488.0,1495704.0,6083,6875
8,1977,1986407.7,219760875,1454268.0,1651632.0,6618,7516
9,1978,2243230.1,222098244,1626753.0,1855849.0,7324,8356
10,1979,2489416.5,224568579,1805001.0,2073257.0,8038,9232
11,1980,2713932.7,227224719,2014396.0,2313160.0,8865,10180
12,1981,3057318.1,229465744,2248034.0,2592915.0,9797,11300
13,1982,3211369.7,231664432,2426023.0,2779794.0,10472,11999
14,1983,3445371.9,233792014,2616717.0,2968676.0,11192,12698
15,1984,3853668.0,235824907,2902515.0,3279488.0,12308,13906
16,1985,4126663.9,237923734,3093703.0,3510471.0,13003,14755
17,1986,4340812.6,240132831,3282912.0,3719647.0,13671,15490
18,1987,4649020.4,242288936,3458192.0,3946593.0,14273,16289
19,1988,5053003.3,244499004,3763033.0,4267813.0,15391,17455
20,1989,5366079.6,246819222,4043179.0,4609667.0,16381,18676
21,1990,5651746.7,249622814,4304512.0,4897821.0,17244,19621
22,1991,5842664.7,252980941,4479825.0,5067291.0,17708,20030
23,1992,6167644.2,256514224,4798176.0,5409920.0,18705,21090
24,1993,6467697.5,259918588,5000936.0,5648732.0,19240,21733
25,1994,6912843.5,263125821,5247927.0,5940128.0,19945,22575
26,1995,7299371.5,266278393,5538573.0,6286143.0,20800,23607
27,1996,7749965.4,269394284,5836986.0,6673186.0,21667,24771
28,1997,8284431.7,272646925,6156053.0,7086935.0,22579,25993
29,1997,8577552.0,272646925,6156053.0,7086935.0,22579,25993
30,1998,9062817.0,275854104,6570164.0,7601594.0,23818,27557
31,1999,9630663.0,279040168,6890679.0,8001563.0,24694,28675
32,2000,10252347.0,282162411,7415075.0,8650325.0,26279,30657
33,2001,10581822.0,284968955,7763912.0,9001839.0,27245,31589
34,2002,10936418.0,287625193,8104480.0,9155663.0,28177,31832
35,2003,11458246.0,290107933,8478455.0,9480901.0,29225,32681
36,2004,12213730.0,292805298,8981157.0,10028781.0,30673,34251
37,2005,13036637.0,295516599,9382761.0,10593946.0,31750,35849
38,2006,13814609.0,298379912,10017121.0,11372589.0,33572,38114
39,2007,14451860.0,301231207,10511373.0,12002204.0,34895,39844
40,2008,14712845.0,304093966,10932716.0,12438527.0,35952,40904
41,2009,14448932.0,306771529,10900400.0,12051307.0,35533,39284
42,2010,14992052.0,309327143,11305991.0,12541995.0,36550,40546
43,2011,15542582.0,311583481,11863823.0,13315478.0,38076,42735
44,2012,16197007.0,313877662,12490913.0,13998383.0,39795,44598
45,2013,16784851.0,316059947,12501275.0,14175503.0,39553,44851
46,2014,17527258.0,318386329,13200377.0,14982715.0,41460,47058
47,2015,18238301.0,320738994,13779697.0,15717140.0,42962,49003
48,2016,18745075.0,323071755,14196265.0,16151881.0,43942,49995
49,2017,19542980.0,325122128,14894009.0,16937582.0,45811,52096
50,2018,20611861.0,326838199,15757141.0,17839255.0,48211,54581
51,2019,21433226.0,328329953,16342277.0,18542262.0,49774,56474

In [48]:
gdp_income_df.describe()

,Year,GDP (Dollars),Population (No. of People),Disposable Personal Income (Millions of Dollars),Personal Income (Millions of Dollars),Per Capita Disposable Personal Income (Dollars),Per Capita Personal Income (Dollars)
count,52.000000,5.200000e+01,5.200000e+01,5.200000e+01,5.200000e+01,52.000000,52.000000
mean,1994.057692,8.542312e+06,2.648071e+08,6.390883e+06,7.251382e+06,22167.307692,25159.500000
std,14.725479,6.111079e+06,3.920696e+07,4.612399e+06,5.216692e+06,13648.024036,15433.452022
min,1969.000000,9.629017e+05,2.012980e+08,6.874250e+05,7.912290e+05,3415.000000,3931.000000
25%,1981.750000,3.172857e+06,2.311148e+08,2.381526e+06,2.733074e+06,10303.250000,11824.250000
50%,1994.500000,7.106108e+06,2.647021e+08,5.393250e+06,6.113136e+06,20372.500000,23091.000000
75%,2006.250000,1.397319e+07,2.990927e+08,1.014068e+07,1.152999e+07,33902.750000,38406.500000
max,2019.000000,2.143323e+07,3.283300e+08,1.634228e+07,1.854226e+07,49774.000000,56474.000000

In [67]:
#Mean for all columns 

mean=pd.DataFrame({"GDP Mean":[gdp_income_df["GDP (Dollars)"].mean()],
"Pop Mean":[gdp_income_df["Population (No. of People)"].mean()],
"DPI Mean":[gdp_income_df["Disposable Personal Income (Millions of Dollars)"].mean()],
"Personal Mean":[gdp_income_df["Personal Income (Millions of Dollars)"].mean()],
"PC Dis Mean":[gdp_income_df["Per Capita Disposable Personal Income (Dollars)"].mean()],
"PC Per In Mean":[gdp_income_df["Per Capita Personal Income (Dollars)"].mean()]})
mean

,GDP Mean,Pop Mean,DPI Mean,Personal Mean,PC Dis Mean,PC Per In Mean
0,8.542312e+06,2.648071e+08,6.390883e+06,7.251382e+06,22167.307692,25159.5

In [68]:
#Median for all columns 
median=pd.DataFrame({"GDP Mean":[gdp_income_df["GDP (Dollars)"].median()],
"Pop Median":[gdp_income_df["Population (No. of People)"].median()],
"DPI Median":[gdp_income_df["Disposable Personal Income (Millions of Dollars)"].median()],
"Personal Median":[gdp_income_df["Personal Income (Millions of Dollars)"].median()],
"PC Dis Median":[gdp_income_df["Per Capita Disposable Personal Income (Dollars)"].median()],
"PC Per In Median":[gdp_income_df["Per Capita Personal Income (Dollars)"].median()]})
median

,GDP Mean,Pop Median,DPI Median,Personal Median,PC Dis Median,PC Per In Median
0,7106107.5,264702107.0,5393250.0,6113135.5,20372.5,23091.0

In [64]:
sts.mode(gdp_income_df["GDP (Dollars)"])

ModeResult(mode=array([962901.7]), count=array([1]))

In [66]:
#Mode for all columns 
# sts.mode(gdp_income_df["GDP (Dollars)"])
mode=pd.DataFrame({"GDP Mode":[gdp_income_df["GDP (Dollars)"].mode()],
"Pop Mode":[gdp_income_df["Population (No. of People)"].mode()],
"DPI Mode":[gdp_income_df["Disposable Personal Income (Millions of Dollars)"].mode()],
"Personal Mode":[gdp_income_df["Personal Income (Millions of Dollars)"].mode()],
"PC Dis Mode":[gdp_income_df["Per Capita Disposable Personal Income (Dollars)"].mode()],
"PC Per In Mode":[gdp_income_df["Per Capita Personal Income (Dollars)"].mode()]})
mode

,GDP Mode,Pop Mode,DPI Mode,Personal Mode,PC Dis Mode,PC Per In Mode
0,0 962901.7 1 1012299.3 2 10971...,0 272646925 dtype: int64,0 6156053.0 dtype: float64,0 7086935.0 dtype: float64,0 22579 dtype: int64,0 25993 dtype: int64

In [35]:
pd.DataFrame({"Mean":[gdp_income_df["GDP (Dollars)"].mean()] })

           Mean
0  8.542312e+06

In [81]:
pd.DataFrame({"STATS": ["Mean","Median","Mode"], 
             "GDP": ["8.542312e+06","7106107.5","7106107.5" ],
             "Pop": ["2.648071e+08","264702107.0","272646925" ],
             "Dis Pers Inc": ["6.390883e+06","5393250.0","6156053.0"],
             "Pers Inc":["7.251382e+06", "6113135.5","7086935.0"],
             "Per Cap Dis Inc": ["22167.307692","20372.5","22579"],
             "Per Cap Pers Inc": ["25159.5","23091.0","25993"]})

,STATS,GDP,Pop,Dis Pers Inc,Pers Inc,Per Cap Dis Inc,Per Cap Pers Inc
0,Mean,8.542312e+06,2.648071e+08,6.390883e+06,7.251382e+06,22167.307692,25159.5
1,Median,7106107.5,264702107.0,5393250.0,6113135.5,20372.5,23091.0
2,Mode,7106107.5,272646925,6156053.0,7086935.0,22579,25993